services:
  accounts:
    image: "manishkonduri008/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - manishkonduri
  loans:
    image: "manishkonduri008/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - manishkonduri
  cards:
    image: "manishkonduri008/cards:s4"
    container_name: cards-ms
    ports:
      - "9001:9001"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - manishkonduri
networks:
  manishkonduri:
    driver: "bridge"